# Library Project with C++20 Modules Configuration

# Basic project information
[project]
name = "math_lib"                 # Project name
version = "1.0.0"                 # Project version
description = "A modern C++ math library" # Project description
namespace = "math"                # Namespace for the code
vendor = "Your Organization"      # Vendor/organization name
contact = "your.email@example.com" # Contact email

# Project type configuration
[project.type]
type = "library"                  # Project type: "library" for a shared or static library

# Dependencies
[dependencies]
fmt = { version = "9.1.0", required = true }
gtest = { version = "1.13.0", required = false }

# Package managers
[package_managers]
cpm = true                        # Use CPM.cmake
conan = true                      # Use Conan as well
vcpkg = false                     # Not using vcpkg
xrepo = false                     # Not using xrepo

# Build configuration
[build]
cpp_standard = "23"               # C++ standard
enable_testing = true             # Enable testing
use_modules = true                # Use C++20 modules

# CMake options
[build.cmake_options]
BUILD_SHARED_LIBS = true          # Build shared libraries
CMAKE_POSITION_INDEPENDENT_CODE = true # Position independent code

# CMake defines
[build.cmake_defines]
VERSION_INFO = "\"${PROJECT_VERSION}\""  # Version info define
EXPORT_SYMBOLS = ""               # Export symbols

# Templates to include
[templates]
main = false                      # No main.cpp for a library
cmake_root = true                 # Include root CMakeLists.txt
cmake_src = true                  # Include src CMakeLists.txt
cmake_config = true               # Include cmake config

# Package manager templates
[templates.package_managers]
conan_config = true               # Include Conan configuration
vcpkg_config = false              # No vcpkg configuration
xrepo_config = false              # No xrepo configuration