# Simple Binary Project Configuration

# Basic project information
[project]
name = "hello_world"              # Project name
version = "0.1.0"                 # Project version
description = "A simple Hello World project" # Project description
namespace = "hello"               # Namespace for the code
vendor = "Your Organization"      # Vendor/organization name
contact = "your.email@example.com" # Contact email

# Project type configuration
[project.type]
type = "binary"                   # Project type: "binary" for executable

# Dependencies
[dependencies]
fmt = { version = "9.1.0", required = true }

# Package managers
[package_managers]
cpm = true                        # Use CPM.cmake for package management
conan = false                     # Not using Conan
vcpkg = false                     # Not using vcpkg
xrepo = false                     # Not using xrepo

# Build configuration
[build]
cpp_standard = "23"               # C++ standard: "23"
enable_testing = true             # Enable testing
use_modules = true                # Use C++20 modules

# CMake options
[build.cmake_options]
BUILD_SHARED_LIBS = false         # Build static libraries

# CMake defines
[build.cmake_defines]
VERSION_INFO = "\"${PROJECT_VERSION}\""  # Version info define
DEBUG_MODE = ""                   # Debug mode define (empty value)

# Templates to include
[templates]
main = true                       # Include main.cpp
cmake_root = true                 # Include root CMakeLists.txt
cmake_src = true                  # Include src CMakeLists.txt
cmake_config = true               # Include cmake config

# Package manager templates - all disabled since we're not using external package managers
[templates.package_managers]
conan_config = false              # No Conan configuration
vcpkg_config = false              # No vcpkg configuration
xrepo_config = false              # No xrepo configuration