# Project Configuration Schema

# Basic project information
[project]
name = "my_project"              # Project name (required)
version = "0.1.0"                # Project version
description = "A simple project" # Project description
namespace = "myproject"          # Namespace for the code (default: project name)
vendor = "Your Organization"     # Vendor/organization name
contact = "your.email@example.com" # Contact email

# Project type configuration
[project.type]
type = "binary"                  # Project type: "binary", "library", "header_only"

# Dependencies
[dependencies]
# Format: package_name = { version = "x.y.z", required = true }
# Example:
# fmt = { version = "9.1.0", required = true }
# spdlog = { version = "1.11.0", required = false }

# Package managers
[package_managers]
cpm = true                       # Use CPM.cmake
conan = false                    # Use Conan
vcpkg = false                    # Use vcpkg
xrepo = false                    # Use xrepo

# Build configuration
[build]
cpp_standard = "23"              # C++ standard: "20", "23"
enable_testing = true            # Enable testing
use_modules = true               # Use C++20 modules

# CMake options
[build.cmake_options]
# Format: option_name = value
# Example:
# BUILD_SHARED_LIBS = true
# CMAKE_POSITION_INDEPENDENT_CODE = true

# CMake defines
[build.cmake_defines]
# Format: define_name = "value"
# Example:
# VERSION_INFO = "\"${PROJECT_VERSION}\""
# DEBUG_MODE = ""

# Templates to include
[templates]
main = true                      # Include main.cpp
cmake_root = true                # Include root CMakeLists.txt
cmake_src = true                 # Include src CMakeLists.txt
cmake_config = true              # Include cmake config

# Package manager templates
[templates.package_managers]
conan_config = false             # Include conan configuration
vcpkg_config = false             # Include vcpkg configuration
xrepo_config = false             # Include xrepo configuration

# Custom templates (optional)
[templates.custom]
# Format: template_name = { source = "path/to/template", destination = "path/in/project" }
# Example:
# readme = { source = "custom/readme.md.template", destination = "README.md" }